#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
读取nar2024databases_sup.xlsx补充数据库并与现有数据合并
"""
import pandas as pd
import json
import re

# 进一步扩展的翻译词典 - 包含更多生物信息学术语
EXTENDED_TRANSLATIONS = {
    # 基础词汇
    'database': '数据库',
    'resource': '资源',
    'tool': '工具',
    'platform': '平台',
    'analysis': '分析',
    'information': '信息',
    'structure': '结构',
    'protein': '蛋白质',
    'gene': '基因',
    'genome': '基因组',
    'plant': '植物',
    'human': '人类',
    'biological': '生物学',
    'molecular': '分子',
    'cellular': '细胞',
    'genetic': '遗传',
    'genomic': '基因组',
    'transcriptomic': '转录组',
    'proteomic': '蛋白质组',
    'metabolomic': '代谢组',
    'bioinformatics': '生物信息学',
    'computational': '计算',
    'sequence': '序列',
    'annotation': '注释',
    'prediction': '预测',
    'classification': '分类',
    'functional': '功能',
    'structural': '结构',
    'evolutionary': '进化',
    'comparative': '比较',
    'cancer': '癌症',
    'disease': '疾病',
    'drug': '药物',
    'therapeutic': '治疗',
    'clinical': '临床',
    'biomarker': '生物标记物',
    'pathway': '通路',
    'network': '网络',
    'interaction': '相互作用',
    'expression': '表达',
    'regulation': '调控',
    'epigenetic': '表观遗传',
    'mutation': '突变',
    'variant': '变异',
    'polymorphism': '多态性',
    'microarray': '芯片',
    'sequencing': '测序',
    'RNA-seq': 'RNA测序',
    'ChIP-seq': 'ChIP测序',
    'single-cell': '单细胞',
    'multi-omics': '多组学',
    'systems biology': '系统生物学',
    'machine learning': '机器学习',
    'artificial intelligence': '人工智能',
    'deep learning': '深度学习',
    'visualization': '可视化',
    'browser': '浏览器',
    'viewer': '查看器',
    'explorer': '探索器',
    'portal': '门户',
    'server': '服务器',
    'service': '服务',
    'web': '网络',
    'online': '在线',
    'interface': '界面',
    'application': '应用',
    'software': '软件',
    'pipeline': '流水线',
    'workflow': '工作流',
    'framework': '框架',
    'library': '库',
    'package': '包',
    'suite': '套件',
    'collection': '集合',
    'repository': '仓库',
    'archive': '档案',
    'hub': '中心',
    'center': '中心',
    'institute': '研究所',
    'laboratory': '实验室',
    'consortium': '联盟',
    'project': '项目',
    'initiative': '倡议',
    'program': '程序',
    'search': '搜索',
    'query': '查询',
    'browse': '浏览',
    'download': '下载',
    'upload': '上传',
    'submit': '提交',
    'access': '访问',
    'retrieve': '检索',
    'filter': '过滤',
    'sort': '排序',
    'compare': '比较',
    'align': '比对',
    'alignment': '比对',
    'blast': 'BLAST比对',
    'similarity': '相似性',
    'homology': '同源性',
    'phylogeny': '系统发育',
    'tree': '进化树',
    'cluster': '聚类',
    'clustering': '聚类',
    'motif': '模式',
    'domain': '功能域',
    'family': '家族',
    'ortholog': '直系同源',
    'paralog': '旁系同源',
    'synteny': '共线性',
    'conservation': '保守性',
    'diversity': '多样性',
    'variation': '变异',
    'association': '关联',
    'correlation': '相关',
    'enrichment': '富集',
    'ontology': '本体',
    'taxonomy': '分类学',
    'nomenclature': '命名法',
    'standard': '标准',
    'format': '格式',
    'protocol': '协议',
    'guideline': '指南',
    'tutorial': '教程',
    'documentation': '文档',
    'manual': '手册',
    'help': '帮助',
    'support': '支持',
    'community': '社区',
    'forum': '论坛',
    'wiki': '维基',
    'blog': '博客',
    'news': '新闻',
    'update': '更新',
    'release': '发布',
    'version': '版本',
    'beta': '测试版',
    'stable': '稳定版',
    'development': '开发',
    'maintenance': '维护',
    'deprecated': '已弃用',
    'legacy': '遗留',
    'migration': '迁移',
    'integration': '整合',
    'api': 'API接口',
    'rest': 'REST接口',
    'json': 'JSON格式',
    'xml': 'XML格式',
    'csv': 'CSV格式',
    'tsv': 'TSV格式',
    'excel': 'Excel格式',
    'pdf': 'PDF格式',
    'image': '图像',
    'figure': '图表',
    'chart': '图表',
    'graph': '图形',
    'plot': '绘图',
    'histogram': '直方图',
    'heatmap': '热图',
    'scatter': '散点图',
    'barplot': '条形图',
    'boxplot': '箱线图',
    'network diagram': '网络图',
    'pathway map': '通路图',
    'genome browser': '基因组浏览器',
    'gene expression': '基因表达',
    'protein structure': '蛋白质结构',
    'molecular dynamics': '分子动力学',
    'docking': '分子对接',
    'virtual screening': '虚拟筛选',
    'drug design': '药物设计',
    'bioactivity': '生物活性',
    'toxicity': '毒性',
    'pharmacology': '药理学',
    'clinical trial': '临床试验',
    'epidemiology': '流行病学',
    'public health': '公共卫生',
    'personalized medicine': '个性化医疗',
    'precision medicine': '精准医疗',
    'biobanking': '生物样本库',
    'biorepository': '生物资源库',
    'specimen': '标本',
    'sample': '样本',
    'cohort': '队列',
    'population': '群体',
    'demographic': '人口统计',
    'ethnicity': '种族',
    'ancestry': '血统',
    'pedigree': '谱系',
    'inheritance': '遗传',
    'mendelian': '孟德尔',
    'complex trait': '复杂性状',
    'quantitative trait': '数量性状',
    'gwas': '全基因组关联研究',
    'snp': '单核苷酸多态性',
    'indel': '插入缺失',
    'cnv': '拷贝数变异',
    'structural variant': '结构变异',
    'chromosome': '染色体',
    'karyotype': '核型',
    'cytogenetics': '细胞遗传学',
    'epigenome': '表观基因组',
    'methylation': '甲基化',
    'histone': '组蛋白',
    'chromatin': '染色质',
    'transcription factor': '转录因子',
    'regulatory element': '调控元件',
    'enhancer': '增强子',
    'promoter': '启动子',
    'silencer': '沉默子',
    'insulator': '绝缘子',
    'miRNA': 'microRNA',
    'lncRNA': '长非编码RNA',
    'circRNA': '环状RNA',
    'piRNA': 'PIWI相互作用RNA',
    'siRNA': '小干扰RNA',
    'ribozyme': '核酶',
    'riboswitch': '核糖开关',
    'splice variant': '剪接变异体',
    'alternative splicing': '选择性剪接',
    'exon': '外显子',
    'intron': '内含子',
    'UTR': '非翻译区',
    'coding sequence': '编码序列',
    'open reading frame': '开放阅读框',
    'start codon': '起始密码子',
    'stop codon': '终止密码子',
    'amino acid': '氨基酸',
    'peptide': '肽',
    'polypeptide': '多肽',
    'protein fold': '蛋白质折叠',
    'secondary structure': '二级结构',
    'tertiary structure': '三级结构',
    'quaternary structure': '四级结构',
    'alpha helix': 'α螺旋',
    'beta sheet': 'β折叠',
    'loop': '环',
    'turn': '转角',
    'coil': '无规卷曲',
    'active site': '活性位点',
    'binding site': '结合位点',
    'allosteric site': '变构位点',
    'catalytic site': '催化位点',
    'enzyme': '酶',
    'kinase': '激酶',
    'phosphatase': '磷酸酶',
    'protease': '蛋白酶',
    'ligase': '连接酶',
    'transferase': '转移酶',
    'hydrolase': '水解酶',
    'oxidoreductase': '氧化还原酶',
    'isomerase': '异构酶',
    'lyase': '裂解酶',
    'receptor': '受体',
    'channel': '通道',
    'transporter': '转运蛋白',
    'carrier': '载体',
    'pump': '泵',
    'exchanger': '交换蛋白',
    'membrane protein': '膜蛋白',
    'cytoplasmic protein': '胞质蛋白',
    'nuclear protein': '核蛋白',
    'mitochondrial protein': '线粒体蛋白',
    'chloroplast protein': '叶绿体蛋白',
    'secreted protein': '分泌蛋白',
    'extracellular protein': '细胞外蛋白',
    'cell surface protein': '细胞表面蛋白',
    'signaling protein': '信号蛋白',
    'structural protein': '结构蛋白',
    'motor protein': '运动蛋白',
    'chaperone': '分子伴侣',
    'heat shock protein': '热休克蛋白',
    'stress response': '应激反应',
    'immune response': '免疫反应',
    'inflammatory response': '炎症反应',
    'cell cycle': '细胞周期',
    'apoptosis': '细胞凋亡',
    'autophagy': '自噬',
    'differentiation': '分化',
    'development': '发育',
    'morphogenesis': '形态发生',
    'organogenesis': '器官发生',
    'embryogenesis': '胚胎发生',
    'stem cell': '干细胞',
    'progenitor cell': '祖细胞',
    'lineage': '谱系',
    'fate': '命运',
    'specification': '规格化',
    'determination': '决定',
    'commitment': '承诺',
    'plasticity': '可塑性',
    'reprogramming': '重编程',
    'regeneration': '再生',
    'repair': '修复',
    'healing': '愈合',
    'homeostasis': '稳态',
    'metabolism': '代谢',
    'catabolism': '分解代谢',
    'anabolism': '合成代谢',
    'glycolysis': '糖酵解',
    'gluconeogenesis': '糖异生',
    'fatty acid synthesis': '脂肪酸合成',
    'beta oxidation': 'β氧化',
    'citric acid cycle': '柠檬酸循环',
    'electron transport': '电子传递',
    'oxidative phosphorylation': '氧化磷酸化',
    'photosynthesis': '光合作用',
    'respiration': '呼吸',
    'fermentation': '发酵',
    'biosynthesis': '生物合成',
    'degradation': '降解',
    'turnover': '周转',
    'flux': '通量',
    'metabolite': '代谢物',
    'metabolome': '代谢组',
    'metabolomics': '代谢组学',
    'lipidomics': '脂质组学',
    'glycomics': '糖组学',
    'peptidomics': '肽组学',
    'interactome': '相互作用组',
    'phenome': '表型组',
    'phenotype': '表型',
    'genotype': '基因型',
    'trait': '性状',
    'character': '特征',
    'feature': '特征',
    'attribute': '属性',
    'property': '性质',
    
    # 2024年新增术语
    'cryo-EM': '冷冻电镜',
    'cryo-electron microscopy': '冷冻电子显微镜',
    'spatial transcriptomics': '空间转录组学',
    'spatial omics': '空间组学',
    'multi-modal': '多模态',
    'multi-scale': '多尺度',
    'high-throughput': '高通量',
    'high-resolution': '高分辨率',
    'real-time': '实时',
    'live-cell': '活细胞',
    'time-lapse': '延时',
    'longitudinal': '纵向',
    'cross-sectional': '横断面',
    'population-scale': '群体规模',
    'large-scale': '大规模',
    'genome-wide': '全基因组',
    'proteome-wide': '全蛋白质组',
    'cell-type': '细胞类型',
    'tissue-specific': '组织特异性',
    'developmental': '发育',
    'aging': '衰老',
    'longevity': '长寿',
    'senescence': '衰老',
    'neurodegeneration': '神经退行性变',
    'neurological': '神经系统',
    'psychiatric': '精神病学',
    'cardiovascular': '心血管',
    'metabolic': '代谢性',
    'autoimmune': '自身免疫',
    'inflammatory': '炎症性',
    'infectious': '感染性',
    'rare disease': '罕见病',
    'orphan disease': '孤儿病',
    'genetic disorder': '遗传疾病',
    'inherited disease': '遗传性疾病',
    'somatic mutation': '体细胞突变',
    'germline mutation': '生殖细胞突变',
    'de novo mutation': '新发突变',
    'frameshift': '移码突变',
    'nonsense': '无义突变',
    'missense': '错义突变',
    'synonymous': '同义突变',
    'splice site': '剪接位点',
    'regulatory variant': '调控变异',
    'loss of function': '功能缺失',
    'gain of function': '功能获得',
    'haploinsufficiency': '单倍体不足',
    'dominant negative': '显性负效应',
    'compound heterozygous': '复合杂合子',
    'consanguineous': '近亲结婚',
    'founder effect': '创始者效应',
    'population bottleneck': '群体瓶颈',
    'genetic drift': '遗传漂变',
    'natural selection': '自然选择',
    'positive selection': '正选择',
    'negative selection': '负选择',
    'balancing selection': '平衡选择',
    'sexual selection': '性选择',
    'coevolution': '协同进化',
    'horizontal gene transfer': '水平基因转移',
    'endosymbiosis': '内共生',
    'speciation': '物种形成',
    'hybridization': '杂交',
    'introgression': '基因渗入',
    'admixture': '混合',
    'population structure': '群体结构',
    'linkage disequilibrium': '连锁不平衡',
    'haplotype': '单体型',
    'recombination': '重组',
    'crossing over': '交换',
    'meiosis': '减数分裂',
    'mitosis': '有丝分裂',
    'cell division': '细胞分裂',
    'chromosome segregation': '染色体分离',
    'spindle checkpoint': '纺锤体检查点',
    'DNA repair': 'DNA修复',
    'DNA damage': 'DNA损伤',
    'oxidative stress': '氧化应激',
    'reactive oxygen species': '活性氧',
    'antioxidant': '抗氧化剂',
    'free radical': '自由基',
    'redox': '氧化还原',
    'electron transfer': '电子转移',
    'proton pump': '质子泵',
    'ion channel': '离子通道',
    'membrane potential': '膜电位',
    'action potential': '动作电位',
    'synaptic transmission': '突触传递',
    'neurotransmitter': '神经递质',
    'hormone': '激素',
    'endocrine': '内分泌',
    'paracrine': '旁分泌',
    'autocrine': '自分泌',
    'signal transduction': '信号转导',
    'second messenger': '第二信使',
    'protein kinase': '蛋白激酶',
    'protein phosphatase': '蛋白磷酸酶',
    'phosphorylation': '磷酸化',
    'dephosphorylation': '去磷酸化',
    'ubiquitination': '泛素化',
    'deubiquitination': '去泛素化',
    'sumoylation': 'SUMO化',
    'acetylation': '乙酰化',
    'deacetylation': '去乙酰化',
    'methylation': '甲基化',
    'demethylation': '去甲基化',
    'hydroxylation': '羟基化',
    'nitrosylation': '亚硝基化',
    'glycosylation': '糖基化',
    'deglycosylation': '去糖基化',
    'lipidation': '脂化',
    'prenylation': '异戊二烯化',
    'palmitoylation': '棕榈酰化',
    'myristoylation': '肉豆蔻酰化',
    'proteolysis': '蛋白质水解',
    'protein degradation': '蛋白质降解',
    'proteasome': '蛋白酶体',
    'lysosome': '溶酶体',
    'endoplasmic reticulum': '内质网',
    'golgi apparatus': '高尔基体',
    'mitochondria': '线粒体',
    'chloroplast': '叶绿体',
    'peroxisome': '过氧化物酶体',
    'ribosome': '核糖体',
    'nucleus': '细胞核',
    'nucleolus': '核仁',
    'cytoplasm': '细胞质',
    'cytoskeleton': '细胞骨架',
    'microtubule': '微管',
    'actin filament': '肌动蛋白丝',
    'intermediate filament': '中间丝',
    'cell membrane': '细胞膜',
    'plasma membrane': '质膜',
    'nuclear membrane': '核膜',
    'nuclear envelope': '核被膜',
    'nuclear pore': '核孔',
    'chromatin': '染色质',
    'heterochromatin': '异染色质',
    'euchromatin': '常染色质',
    'nucleosome': '核小体',
    'histone': '组蛋白',
    'DNA methylation': 'DNA甲基化',
    'histone modification': '组蛋白修饰',
    'chromatin remodeling': '染色质重塑',
    'transcriptional regulation': '转录调控',
    'post-transcriptional regulation': '转录后调控',
    'translational regulation': '翻译调控',
    'post-translational modification': '翻译后修饰',
    'RNA processing': 'RNA加工',
    'RNA splicing': 'RNA剪接',
    'RNA editing': 'RNA编辑',
    'RNA stability': 'RNA稳定性',
    'RNA localization': 'RNA定位',
    'protein folding': '蛋白质折叠',
    'protein misfolding': '蛋白质错误折叠',
    'protein aggregation': '蛋白质聚集',
    'amyloid': '淀粉样蛋白',
    'prion': '朊病毒',
    'conformational change': '构象变化',
    'allosteric regulation': '变构调节',
    'enzyme kinetics': '酶动力学',
    'michaelis-menten': '米氏动力学',
    'competitive inhibition': '竞争性抑制',
    'non-competitive inhibition': '非竞争性抑制',
    'feedback inhibition': '反馈抑制',
    'cooperativity': '协同性',
    'hill coefficient': '希尔系数',
    'binding affinity': '结合亲和力',
    'dissociation constant': '解离常数',
    'equilibrium constant': '平衡常数',
    'thermodynamics': '热力学',
    'enthalpy': '焓',
    'entropy': '熵',
    'free energy': '自由能',
    'activation energy': '活化能',
    'transition state': '过渡态',
    'catalysis': '催化',
    'enzyme catalysis': '酶催化',
    'chemical reaction': '化学反应',
    'biochemical pathway': '生化途径',
    'metabolic pathway': '代谢途径',
    'signaling pathway': '信号通路',
    'regulatory pathway': '调控通路',
    'feedback loop': '反馈环',
    'feedforward loop': '前馈环',
    'regulatory network': '调控网络',
    'gene regulatory network': '基因调控网络',
    'protein interaction network': '蛋白相互作用网络',
    'metabolic network': '代谢网络',
    'signaling network': '信号网络',
    'systems biology': '系统生物学',
    'network biology': '网络生物学',
    'computational biology': '计算生物学',
    'bioinformatics': '生物信息学',
    'biostatistics': '生物统计学',
    'mathematical modeling': '数学建模',
    'statistical analysis': '统计分析',
    'data mining': '数据挖掘',
    'pattern recognition': '模式识别',
    'feature selection': '特征选择',
    'dimensionality reduction': '降维',
    'principal component analysis': '主成分分析',
    'cluster analysis': '聚类分析',
    'phylogenetic analysis': '系统发育分析',
    'sequence alignment': '序列比对',
    'multiple sequence alignment': '多序列比对',
    'pairwise alignment': '双序列比对',
    'global alignment': '全局比对',
    'local alignment': '局部比对',
    'sequence similarity': '序列相似性',
    'sequence identity': '序列一致性',
    'sequence homology': '序列同源性',
    'evolutionary distance': '进化距离',
    'molecular clock': '分子钟',
    'substitution rate': '替换速率',
    'mutation rate': '突变速率',
    'selection pressure': '选择压力',
    'fitness': '适应度',
    'evolutionary fitness': '进化适应度',
    'reproductive success': '繁殖成功',
    'survival': '生存',
    'adaptation': '适应',
    'evolutionary adaptation': '进化适应',
    'convergent evolution': '趋同进化',
    'divergent evolution': '趋异进化',
    'parallel evolution': '平行进化',
    'molecular evolution': '分子进化',
    'genome evolution': '基因组进化',
    'protein evolution': '蛋白质进化',
    'gene duplication': '基因重复',
    'gene loss': '基因缺失',
    'pseudogene': '假基因',
    'orthologous': '直系同源',
    'paralogous': '旁系同源',
    'homologous': '同源',
    'analogous': '类似',
    'conservation': '保守性',
    'conserved sequence': '保守序列',
    'conserved domain': '保守域',
    'functional conservation': '功能保守性',
    'structural conservation': '结构保守性',
    'synteny': '共线性',
    'genome synteny': '基因组共线性',
    'comparative genomics': '比较基因组学',
    'phylogenomics': '系统发育基因组学',
    'population genomics': '群体基因组学',
    'landscape genomics': '景观基因组学',
    'ecological genomics': '生态基因组学',
    'environmental genomics': '环境基因组学',
    'metagenomics': '宏基因组学',
    'microbiome': '微生物组',
    'microbiota': '微生物群',
    'symbiosis': '共生',
    'mutualism': '互利共生',
    'commensalism': '偏利共生',
    'parasitism': '寄生',
    'pathogenesis': '致病机制',
    'virulence': '毒力',
    'antibiotic resistance': '抗生素抗性',
    'drug resistance': '耐药性',
    'antimicrobial': '抗菌',
    'antiviral': '抗病毒',
    'antifungal': '抗真菌',
    'vaccine': '疫苗',
    'immunization': '免疫接种',
    'immunity': '免疫',
    'innate immunity': '先天免疫',
    'adaptive immunity': '适应性免疫',
    'humoral immunity': '体液免疫',
    'cellular immunity': '细胞免疫',
    'antibody': '抗体',
    'antigen': '抗原',
    'epitope': '表位',
    'paratope': '副位',
    'immunoglobulin': '免疫球蛋白',
    'major histocompatibility complex': '主要组织相容性复合体',
    'T cell': 'T细胞',
    'B cell': 'B细胞',
    'natural killer cell': '自然杀伤细胞',
    'dendritic cell': '树突状细胞',
    'macrophage': '巨噬细胞',
    'neutrophil': '中性粒细胞',
    'eosinophil': '嗜酸性粒细胞',
    'basophil': '嗜碱性粒细胞',
    'mast cell': '肥大细胞',
    'cytokine': '细胞因子',
    'chemokine': '趋化因子',
    'interleukin': '白细胞介素',
    'interferon': '干扰素',
    'tumor necrosis factor': '肿瘤坏死因子',
    'growth factor': '生长因子',
    'angiogenesis': '血管生成',
    'apoptosis': '细胞凋亡',
    'necrosis': '坏死',
    'autophagy': '自噬',
    'senescence': '衰老',
    'cell cycle': '细胞周期',
    'cell proliferation': '细胞增殖',
    'cell differentiation': '细胞分化',
    'stem cell': '干细胞',
    'pluripotent': '多能性',
    'totipotent': '全能性',
    'embryonic stem cell': '胚胎干细胞',
    'induced pluripotent stem cell': '诱导多能干细胞',
    'adult stem cell': '成体干细胞',
    'mesenchymal stem cell': '间充质干细胞',
    'hematopoietic stem cell': '造血干细胞',
    'neural stem cell': '神经干细胞',
    'cancer stem cell': '癌症干细胞',
    'tumor': '肿瘤',
    'neoplasm': '肿瘤',
    'malignant': '恶性',
    'benign': '良性',
    'metastasis': '转移',
    'invasion': '侵袭',
    'oncogene': '癌基因',
    'tumor suppressor': '肿瘤抑制基因',
    'carcinogenesis': '致癌过程',
    'tumorigenesis': '肿瘤发生',
    'oncology': '肿瘤学',
    'chemotherapy': '化疗',
    'radiotherapy': '放疗',
    'immunotherapy': '免疫治疗',
    'targeted therapy': '靶向治疗',
    'precision medicine': '精准医疗',
    'personalized medicine': '个性化医疗',
    'companion diagnostic': '伴随诊断',
    'biomarker': '生物标记物',
    'prognostic biomarker': '预后生物标记物',
    'predictive biomarker': '预测生物标记物',
    'diagnostic biomarker': '诊断生物标记物',
    'liquid biopsy': '液体活检',
    'circulating tumor cell': '循环肿瘤细胞',
    'circulating tumor DNA': '循环肿瘤DNA',
    'cell-free DNA': '游离DNA',
    'exosome': '外泌体',
    'extracellular vesicle': '细胞外囊泡',
    'microparticle': '微粒',
    'nanoparticle': '纳米粒子',
    'drug delivery': '药物递送',
    'pharmacokinetics': '药物动力学',
    'pharmacodynamics': '药效学',
    'toxicology': '毒理学',
    'adverse drug reaction': '药物不良反应',
    'drug-drug interaction': '药物相互作用',
    'pharmacogenomics': '药物基因组学',
    'pharmacogenetics': '药物遗传学',
    'dose-response': '剂量反应',
    'therapeutic window': '治疗窗',
    'minimum effective concentration': '最小有效浓度',
    'maximum tolerated dose': '最大耐受剂量',
    'half-life': '半衰期',
    'clearance': '清除率',
    'bioavailability': '生物利用度',
    'absorption': '吸收',
    'distribution': '分布',
    'metabolism': '代谢',
    'excretion': '排泄',
    'first-pass effect': '首过效应',
    'cytochrome P450': '细胞色素P450',
    'phase I metabolism': 'I相代谢',
    'phase II metabolism': 'II相代谢',
    'conjugation': '结合反应',
    'glucuronidation': '葡萄糖醛酸化',
    'sulfation': '硫酸化',
    'acetylation': '乙酰化',
    'methylation': '甲基化',
    'oxidation': '氧化',
    'reduction': '还原',
    'hydrolysis': '水解',
    'deamination': '脱氨',
    'dealkylation': '脱烷基',
    'hydroxylation': '羟基化',
    'epoxidation': '环氧化',
    'dehydrogenation': '脱氢',
    'isomerization': '异构化',
    'cyclization': '环化',
    'rearrangement': '重排',
    'fragmentation': '裂解',
    'polymerization': '聚合',
    'cross-linking': '交联',
    'covalent bond': '共价键',
    'hydrogen bond': '氢键',
    'ionic bond': '离子键',
    'van der waals force': '范德华力',
    'hydrophobic interaction': '疏水相互作用',
    'electrostatic interaction': '静电相互作用',
    'dipole-dipole interaction': '偶极-偶极相互作用',
    'london dispersion force': '伦敦色散力',
    'pi-pi stacking': 'π-π堆积',
    'cation-pi interaction': '阳离子-π相互作用',
    'salt bridge': '盐桥',
    'disulfide bond': '二硫键',
    'peptide bond': '肽键',
    'glycosidic bond': '糖苷键',
    'phosphodiester bond': '磷酸二酯键',
    'ester bond': '酯键',
    'ether bond': '醚键',
    'amide bond': '酰胺键',
    'thioester bond': '硫酯键',
    'coordination bond': '配位键',
    'metal coordination': '金属配位',
    'chelation': '螯合',
    'ligand': '配体',
    'cofactor': '辅因子',
    'coenzyme': '辅酶',
    'prosthetic group': '辅基',
    'heme': '血红素',
    'chlorophyll': '叶绿素',
    'flavin': '黄素',
    'nicotinamide': '烟酰胺',
    'thiamine': '硫胺素',
    'riboflavin': '核黄素',
    'niacin': '烟酸',
    'pantothenic acid': '泛酸',
    'pyridoxine': '吡哆醇',
    'biotin': '生物素',
    'folate': '叶酸',
    'cobalamin': '钴胺素',
    'ascorbic acid': '抗坏血酸',
    'tocopherol': '生育酚',
    'retinol': '视黄醇',
    'calciferol': '钙化醇',
    'phylloquinone': '叶绿醌',
    'menaquinone': '甲萘醌',
    'carotenoid': '类胡萝卜素',
    'flavonoid': '黄酮类',
    'phenolic compound': '酚类化合物',
    'alkaloid': '生物碱',
    'terpenoid': '萜类',
    'steroid': '类固醇',
    'lipid': '脂质',
    'fatty acid': '脂肪酸',
    'phospholipid': '磷脂',
    'glycolipid': '糖脂',
    'sphingolipid': '鞘脂',
    'cholesterol': '胆固醇',
    'triglyceride': '甘油三酯',
    'carbohydrate': '碳水化合物',
    'monosaccharide': '单糖',
    'disaccharide': '双糖',
    'oligosaccharide': '寡糖',
    'polysaccharide': '多糖',
    'glycoprotein': '糖蛋白',
    'proteoglycan': '蛋白聚糖',
    'glycosaminoglycan': '糖胺聚糖',
    'nucleic acid': '核酸',
    'nucleotide': '核苷酸',
    'nucleoside': '核苷',
    'purine': '嘌呤',
    'pyrimidine': '嘧啶',
    'adenine': '腺嘌呤',
    'guanine': '鸟嘌呤',
    'cytosine': '胞嘧啶',
    'thymine': '胸腺嘧啶',
    'uracil': '尿嘧啶',
    'ribose': '核糖',
    'deoxyribose': '脱氧核糖',
    'phosphate': '磷酸',
    'double helix': '双螺旋',
    'base pair': '碱基对',
    'watson-crick pairing': '沃森-克里克配对',
    'major groove': '大沟',
    'minor groove': '小沟',
    'supercoiling': '超螺旋',
    'topoisomerase': '拓扑异构酶',
    'helicase': '解旋酶',
    'primase': '引物酶',
    'DNA polymerase': 'DNA聚合酶',
    'RNA polymerase': 'RNA聚合酶',
    'ligase': '连接酶',
    'nuclease': '核酸酶',
    'exonuclease': '外切核酸酶',
    'endonuclease': '内切核酸酶',
    'restriction enzyme': '限制性内切酶',
    'reverse transcriptase': '逆转录酶',
    'telomerase': '端粒酶',
    'telomere': '端粒',
    'centromere': '着丝粒',
    'kinetochore': '着丝点',
    'spindle fiber': '纺锤丝',
    'centriole': '中心粒',
    'centrosome': '中心体',
    'flagellum': '鞭毛',
    'cilium': '纤毛',
    'pilus': '菌毛',
    'cell wall': '细胞壁',
    'peptidoglycan': '肽聚糖',
    'chitin': '几丁质',
    'cellulose': '纤维素',
    'lignin': '木质素',
    'pectin': '果胶',
    'hemicellulose': '半纤维素',
    'starch': '淀粉',
    'glycogen': '糖原',
    'inulin': '菊糖',
    'xylan': '木聚糖',
    'mannan': '甘露聚糖',
    'galactan': '半乳聚糖',
    'arabinan': '阿拉伯聚糖',
    'glucan': '葡聚糖',
    'fructan': '果聚糖',
    'dextran': '右旋糖酐',
    'levan': '果聚糖',
    'pullulan': '支链淀粉',
    'amylose': '直链淀粉',
    'amylopectin': '支链淀粉',
    'maltose': '麦芽糖',
    'sucrose': '蔗糖',
    'lactose': '乳糖',
    'trehalose': '海藻糖',
    'glucose': '葡萄糖',
    'fructose': '果糖',
    'galactose': '半乳糖',
    'mannose': '甘露糖',
    'xylose': '木糖',
    'arabinose': '阿拉伯糖',
    'rhamnose': '鼠李糖',
    'fucose': '岩藻糖',
    'glucuronic acid': '葡萄糖醛酸',
    'galacturonic acid': '半乳糖醛酸',
    'neuraminic acid': '神经氨酸',
    'sialic acid': '唾液酸',
    'hyaluronic acid': '透明质酸',
    'chondroitin sulfate': '硫酸软骨素',
    'heparin': '肝素',
    'keratan sulfate': '角质素硫酸',
    'dermatan sulfate': '硫酸皮肤素'
}

# 分类规则 - 更新后的分类
UPDATED_CATEGORIES = {
    'protein': {
        'name': '蛋白质',
        'keywords': ['protein', 'structure', 'fold', 'domain', 'isoform', 'alphafold', 'structural', 'amino acid', 'peptide', 'enzyme', 'kinase', 'phosphatase', 'protease']
    },
    'genomics': {
        'name': '基因组学',
        'keywords': ['genome', 'genomic', 'gene', 'genetic', 'dna', 'sequence', 'chromosome', 'variant', 'mutation', 'gwas', 'snp', 'indel', 'cnv', 'structural variant']
    },
    'plant': {
        'name': '植物生物学',
        'keywords': ['plant', 'arabidopsis', 'rice', 'asteraceae', 'botanical', 'crop', 'agriculture', 'photosynthesis', 'chloroplast', 'wheat', 'maize', 'soybean']
    },
    'medical': {
        'name': '医学生物学',
        'keywords': ['human', 'disease', 'clinical', 'medical', 'cancer', 'drug', 'therapeutic', 'biomarker', 'patient', 'health', 'tumor', 'oncology', 'pharmacology']
    },
    'microbiology': {
        'name': '微生物学',
        'keywords': ['bacteria', 'virus', 'viral', 'microbial', 'pathogen', 'microbe', 'prokaryotic', 'archaea', 'fungal', 'yeast', 'microbiome']
    },
    'evolution': {
        'name': '进化生物学',
        'keywords': ['evolution', 'phylogen', 'comparative', 'species', 'evolutionary', 'taxonomy', 'tree', 'ancestral', 'divergence', 'selection']
    },
    'omics': {
        'name': '组学',
        'keywords': ['omics', 'transcriptome', 'proteome', 'metabolome', 'multi-omics', 'rna-seq', 'chip-seq', 'single-cell', 'epigenome', 'spatial', 'lipidomics']
    },
    'tools': {
        'name': '生物信息工具',
        'keywords': ['tool', 'analysis', 'resource', 'platform', 'service', 'computational', 'bioinformatics', 'software', 'web', 'online', 'server', 'portal', 'browser', 'viewer', 'pipeline', 'workflow']
    }
}

def categorize_database(name, description):
    """根据名称和描述给数据库分类"""
    text = (name + ' ' + description).lower()
    
    for category_id, category_info in UPDATED_CATEGORIES.items():
        for keyword in category_info['keywords']:
            if keyword.lower() in text:
                return category_id
    
    return 'tools'  # 默认分类

def translate_description(description):
    """增强版翻译描述"""
    if not description or description == 'nan' or str(description) == 'nan':
        return description
    
    description = str(description)
    original_desc = description
    
    # 直接查找完整短语的翻译
    desc_lower = description.lower()
    
    # 按长度排序，优先匹配长短语
    sorted_translations = sorted(EXTENDED_TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True)
    
    translated_desc = description
    for eng, chn in sorted_translations:
        if eng.lower() in desc_lower:
            # 使用正则表达式进行词边界匹配
            pattern = r'\b' + re.escape(eng) + r'\b'
            translated_desc = re.sub(pattern, chn, translated_desc, flags=re.IGNORECASE)
    
    # 如果翻译后与原文差异较大，返回翻译结果
    if translated_desc != original_desc:
        return translated_desc
    
    # 否则返回原文
    return description

def read_2024_sup_databases():
    """读取2024年补充数据库信息并与现有数据合并"""
    try:
        # 读取2024年补充Excel文件
        df_2024_sup = pd.read_excel('nar2024databases_sup.xlsx')
        
        print("2024年补充Excel文件的列名:")
        print(df_2024_sup.columns.tolist())
        print(f"\n2024年补充数据形状: {df_2024_sup.shape}")
        
        # 显示前几行数据
        print("\n前5行2024年补充数据:")
        print(df_2024_sup.head())
        
        # 读取现有数据
        with open('databases_processed.json', 'r', encoding='utf-8') as f:
            existing_data = json.load(f)
        
        print(f"\n现有数据数量: {len(existing_data)}")
        
        # 处理2024年补充数据
        new_databases = []
        start_id = len(existing_data) + 1
        
        for index, row in df_2024_sup.iterrows():
            db_info = {
                'id': start_id + index,
                'name': str(row.get('Database name', '')),
                'url': str(row.get('URL', '')),
                'short_description': str(row.get('Short description', '')),
                'description': str(row.get('Short description', '')),
                'last_update': '',
                'access': 'Free',
                'data_type': 'database',  # 标记为数据库类型
                'resource_type': 'database'   # 区分数据库和网站
            }
            
            # 添加分类
            category = categorize_database(db_info['name'], db_info['short_description'])
            db_info['category'] = category
            db_info['category_name'] = UPDATED_CATEGORIES[category]['name']
            
            # 添加中文翻译
            db_info['short_description_zh'] = translate_description(db_info['short_description'])
            
            new_databases.append(db_info)
        
        # 合并数据
        all_resources = existing_data + new_databases
        
        # 保存合并后的数据
        with open('databases_processed.json', 'w', encoding='utf-8') as f:
            json.dump(all_resources, f, ensure_ascii=False, indent=2)
        
        print(f"\n成功添加了 {len(new_databases)} 个2024年补充数据库")
        print(f"总资源数量: {len(all_resources)}")
        
        # 统计分类和类型
        category_stats = {}
        db_stats = {}
        web_stats = {}
        
        for resource in all_resources:
            cat = resource['category']
            res_type = resource.get('resource_type', 'database')
            
            if cat not in category_stats:
                category_stats[cat] = 0
                db_stats[cat] = 0
                web_stats[cat] = 0
            
            category_stats[cat] += 1
            if res_type == 'database':
                db_stats[cat] += 1
            else:
                web_stats[cat] += 1
        
        print("\n更新后的资源分类统计:")
        for cat, count in category_stats.items():
            print(f"  {UPDATED_CATEGORIES[cat]['name']}: {count}个 (数据库: {db_stats[cat]}, 网站: {web_stats[cat]})")
        
        # 统计总数
        total_databases = sum(db_stats.values())
        total_websites = sum(web_stats.values())
        print(f"\n总计: {len(all_resources)}个资源 (数据库: {total_databases}, 网站: {total_websites})")
        
        return all_resources
        
    except Exception as e:
        print(f"处理2024年补充数据时出错: {e}")
        import traceback
        traceback.print_exc()
        return []

if __name__ == "__main__":
    resources = read_2024_sup_databases()
