#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
读取nar2025web.xlsx生物信息web网站并与现有数据合并
"""
import pandas as pd
import json
import re

# 扩展翻译词典 - 专门针对web网站和工具
WEB_TRANSLATIONS = {
    'database': '数据库',
    'resource': '资源',
    'tool': '工具',
    'platform': '平台',
    'analysis': '分析',
    'information': '信息',
    'structure': '结构',
    'protein': '蛋白质',
    'gene': '基因',
    'genome': '基因组',
    'plant': '植物',
    'human': '人类',
    'biological': '生物学',
    'molecular': '分子',
    'cellular': '细胞',
    'genetic': '遗传',
    'genomic': '基因组',
    'transcriptomic': '转录组',
    'proteomic': '蛋白质组',
    'metabolomic': '代谢组',
    'bioinformatics': '生物信息学',
    'computational': '计算',
    'sequence': '序列',
    'annotation': '注释',
    'prediction': '预测',
    'classification': '分类',
    'functional': '功能',
    'structural': '结构',
    'evolutionary': '进化',
    'comparative': '比较',
    'cancer': '癌症',
    'disease': '疾病',
    'drug': '药物',
    'therapeutic': '治疗',
    'clinical': '临床',
    'biomarker': '生物标记物',
    'pathway': '通路',
    'network': '网络',
    'interaction': '相互作用',
    'expression': '表达',
    'regulation': '调控',
    'epigenetic': '表观遗传',
    'mutation': '突变',
    'variant': '变异',
    'polymorphism': '多态性',
    'microarray': '芯片',
    'sequencing': '测序',
    'RNA-seq': 'RNA测序',
    'ChIP-seq': 'ChIP测序',
    'single-cell': '单细胞',
    'multi-omics': '多组学',
    'systems biology': '系统生物学',
    'machine learning': '机器学习',
    'artificial intelligence': '人工智能',
    'deep learning': '深度学习',
    'visualization': '可视化',
    'browser': '浏览器',
    'viewer': '查看器',
    'explorer': '探索器',
    'portal': '门户',
    'server': '服务器',
    'service': '服务',
    'web': '网络',
    'online': '在线',
    'interface': '界面',
    'application': '应用',
    'software': '软件',
    'pipeline': '流水线',
    'workflow': '工作流',
    'framework': '框架',
    'library': '库',
    'package': '包',
    'suite': '套件',
    'collection': '集合',
    'repository': '仓库',
    'archive': '档案',
    'hub': '中心',
    'center': '中心',
    'institute': '研究所',
    'laboratory': '实验室',
    'consortium': '联盟',
    'project': '项目',
    'initiative': '倡议',
    'program': '程序',
    'search': '搜索',
    'query': '查询',
    'browse': '浏览',
    'download': '下载',
    'upload': '上传',
    'submit': '提交',
    'access': '访问',
    'retrieve': '检索',
    'filter': '过滤',
    'sort': '排序',
    'compare': '比较',
    'align': '比对',
    'blast': 'BLAST比对',
    'similarity': '相似性',
    'homology': '同源性',
    'phylogeny': '系统发育',
    'tree': '进化树',
    'cluster': '聚类',
    'motif': '模式',
    'domain': '功能域',
    'family': '家族',
    'ortholog': '直系同源',
    'paralog': '旁系同源',
    'synteny': '共线性',
    'conservation': '保守性',
    'diversity': '多样性',
    'variation': '变异',
    'association': '关联',
    'correlation': '相关',
    'enrichment': '富集',
    'ontology': '本体',
    'taxonomy': '分类学',
    'nomenclature': '命名法',
    'standard': '标准',
    'format': '格式',
    'protocol': '协议',
    'guideline': '指南',
    'tutorial': '教程',
    'documentation': '文档',
    'manual': '手册',
    'help': '帮助',
    'support': '支持',
    'community': '社区',
    'forum': '论坛',
    'wiki': '维基',
    'blog': '博客',
    'news': '新闻',
    'update': '更新',
    'release': '发布',
    'version': '版本',
    'beta': '测试版',
    'stable': '稳定版',
    'development': '开发',
    'maintenance': '维护',
    'deprecated': '已弃用',
    'legacy': '遗留',
    'migration': '迁移',
    'integration': '整合',
    'api': 'API接口',
    'rest': 'REST接口',
    'json': 'JSON格式',
    'xml': 'XML格式',
    'csv': 'CSV格式',
    'tsv': 'TSV格式',
    'excel': 'Excel格式',
    'pdf': 'PDF格式',
    'image': '图像',
    'figure': '图表',
    'chart': '图表',
    'graph': '图形',
    'plot': '绘图',
    'histogram': '直方图',
    'heatmap': '热图',
    'scatter': '散点图',
    'barplot': '条形图',
    'boxplot': '箱线图',
    'network diagram': '网络图',
    'pathway map': '通路图',
    'genome browser': '基因组浏览器',
    'gene expression': '基因表达',
    'protein structure': '蛋白质结构',
    'molecular dynamics': '分子动力学',
    'docking': '分子对接',
    'virtual screening': '虚拟筛选',
    'drug design': '药物设计',
    'bioactivity': '生物活性',
    'toxicity': '毒性',
    'pharmacology': '药理学',
    'clinical trial': '临床试验',
    'epidemiology': '流行病学',
    'public health': '公共卫生',
    'personalized medicine': '个性化医疗',
    'precision medicine': '精准医疗',
    'biobanking': '生物样本库',
    'biorepository': '生物资源库',
    'specimen': '标本',
    'sample': '样本',
    'cohort': '队列',
    'population': '群体',
    'demographic': '人口统计',
    'ethnicity': '种族',
    'ancestry': '血统',
    'pedigree': '谱系',
    'inheritance': '遗传',
    'mendelian': '孟德尔',
    'complex trait': '复杂性状',
    'quantitative trait': '数量性状',
    'gwas': '全基因组关联研究',
    'snp': '单核苷酸多态性',
    'indel': '插入缺失',
    'cnv': '拷贝数变异',
    'structural variant': '结构变异',
    'chromosome': '染色体',
    'karyotype': '核型',
    'cytogenetics': '细胞遗传学',
    'epigenome': '表观基因组',
    'methylation': '甲基化',
    'histone': '组蛋白',
    'chromatin': '染色质',
    'transcription factor': '转录因子',
    'regulatory element': '调控元件',
    'enhancer': '增强子',
    'promoter': '启动子',
    'silencer': '沉默子',
    'insulator': '绝缘子',
    'miRNA': 'microRNA',
    'lncRNA': '长非编码RNA',
    'circRNA': '环状RNA',
    'piRNA': 'PIWI相互作用RNA',
    'siRNA': '小干扰RNA',
    'ribozyme': '核酶',
    'riboswitch': '核糖开关',
    'splice variant': '剪接变异体',
    'alternative splicing': '选择性剪接',
    'exon': '外显子',
    'intron': '内含子',
    'UTR': '非翻译区',
    'coding sequence': '编码序列',
    'open reading frame': '开放阅读框',
    'start codon': '起始密码子',
    'stop codon': '终止密码子',
    'amino acid': '氨基酸',
    'peptide': '肽',
    'polypeptide': '多肽',
    'protein fold': '蛋白质折叠',
    'secondary structure': '二级结构',
    'tertiary structure': '三级结构',
    'quaternary structure': '四级结构',
    'alpha helix': 'α螺旋',
    'beta sheet': 'β折叠',
    'loop': '环',
    'turn': '转角',
    'coil': '无规卷曲',
    'active site': '活性位点',
    'binding site': '结合位点',
    'allosteric site': '变构位点',
    'catalytic site': '催化位点',
    'enzyme': '酶',
    'kinase': '激酶',
    'phosphatase': '磷酸酶',
    'protease': '蛋白酶',
    'ligase': '连接酶',
    'transferase': '转移酶',
    'hydrolase': '水解酶',
    'oxidoreductase': '氧化还原酶',
    'isomerase': '异构酶',
    'lyase': '裂解酶',
    'receptor': '受体',
    'channel': '通道',
    'transporter': '转运蛋白',
    'carrier': '载体',
    'pump': '泵',
    'exchanger': '交换蛋白',
    'membrane protein': '膜蛋白',
    'cytoplasmic protein': '胞质蛋白',
    'nuclear protein': '核蛋白',
    'mitochondrial protein': '线粒体蛋白',
    'chloroplast protein': '叶绿体蛋白',
    'secreted protein': '分泌蛋白',
    'extracellular protein': '细胞外蛋白',
    'cell surface protein': '细胞表面蛋白',
    'signaling protein': '信号蛋白',
    'structural protein': '结构蛋白',
    'motor protein': '运动蛋白',
    'chaperone': '分子伴侣',
    'heat shock protein': '热休克蛋白',
    'stress response': '应激反应',
    'immune response': '免疫反应',
    'inflammatory response': '炎症反应',
    'cell cycle': '细胞周期',
    'apoptosis': '细胞凋亡',
    'autophagy': '自噬',
    'differentiation': '分化',
    'development': '发育',
    'morphogenesis': '形态发生',
    'organogenesis': '器官发生',
    'embryogenesis': '胚胎发生',
    'stem cell': '干细胞',
    'progenitor cell': '祖细胞',
    'lineage': '谱系',
    'fate': '命运',
    'specification': '规格化',
    'determination': '决定',
    'commitment': '承诺',
    'plasticity': '可塑性',
    'reprogramming': '重编程',
    'regeneration': '再生',
    'repair': '修复',
    'healing': '愈合',
    'homeostasis': '稳态',
    'metabolism': '代谢',
    'catabolism': '分解代谢',
    'anabolism': '合成代谢',
    'glycolysis': '糖酵解',
    'gluconeogenesis': '糖异生',
    'fatty acid synthesis': '脂肪酸合成',
    'beta oxidation': 'β氧化',
    'citric acid cycle': '柠檬酸循环',
    'electron transport': '电子传递',
    'oxidative phosphorylation': '氧化磷酸化',
    'photosynthesis': '光合作用',
    'respiration': '呼吸',
    'fermentation': '发酵',
    'biosynthesis': '生物合成',
    'degradation': '降解',
    'turnover': '周转',
    'flux': '通量',
    'metabolite': '代谢物',
    'metabolome': '代谢组',
    'metabolomics': '代谢组学',
    'lipidomics': '脂质组学',
    'glycomics': '糖组学',
    'peptidomics': '肽组学',
    'interactome': '相互作用组',
    'phenome': '表型组',
    'phenotype': '表型',
    'genotype': '基因型',
    'trait': '性状',
    'character': '特征',
    'feature': '特征',
    'attribute': '属性',
    'property': '性质',
    'quality': '质量',
    'quantity': '数量',
    'measurement': '测量',
    'assay': '检测',
    'experiment': '实验',
    'study': '研究',
    'investigation': '调查',
    'survey': '调查',
    'screen': '筛选',
    'test': '测试',
    'trial': '试验',
    'validation': '验证',
    'confirmation': '确认',
    'replication': '重复',
    'reproducibility': '可重复性',
    'reliability': '可靠性',
    'accuracy': '准确性',
    'precision': '精确性',
    'sensitivity': '敏感性',
    'specificity': '特异性',
    'resolution': '分辨率',
    'coverage': '覆盖度',
    'depth': '深度',
    'breadth': '广度',
    'scope': '范围',
    'scale': '规模',
    'size': '大小',
    'length': '长度',
    'width': '宽度',
    'height': '高度',
    'volume': '体积',
    'area': '面积',
    'density': '密度',
    'concentration': '浓度',
    'intensity': '强度',
    'magnitude': '幅度',
    'amplitude': '振幅',
    'frequency': '频率',
    'rate': '速率',
    'velocity': '速度',
    'acceleration': '加速度',
    'time': '时间',
    'duration': '持续时间',
    'period': '周期',
    'interval': '间隔',
    'phase': '相位',
    'stage': '阶段',
    'step': '步骤',
    'process': '过程',
    'procedure': '程序',
    'method': '方法',
    'technique': '技术',
    'approach': '方法',
    'strategy': '策略',
    'algorithm': '算法',
    'model': '模型',
    'simulation': '模拟',
    'modeling': '建模',
    'prediction': '预测',
    'forecast': '预报',
    'estimation': '估计',
    'calculation': '计算',
    'computation': '计算',
    'processing': '处理',
    'transformation': '转换',
    'conversion': '转换',
    'translation': '翻译',
    'interpretation': '解释',
    'explanation': '说明',
    'description': '描述',
    'characterization': '表征',
    'identification': '鉴定',
    'recognition': '识别',
    'detection': '检测',
    'discovery': '发现',
    'exploration': '探索',
    'investigation': '调查',
    'analysis': '分析',
    'evaluation': '评估',
    'assessment': '评价',
    'comparison': '比较',
    'contrast': '对比',
    'correlation': '相关',
    'association': '关联',
    'relationship': '关系',
    'connection': '连接',
    'link': '链接',
    'bond': '键',
    'binding': '结合',
    'attachment': '附着',
    'adhesion': '粘附',
    'interaction': '相互作用',
    'communication': '通讯',
    'signaling': '信号传导',
    'transduction': '转导',
    'transmission': '传递',
    'propagation': '传播',
    'diffusion': '扩散',
    'transport': '运输',
    'trafficking': '转运',
    'localization': '定位',
    'distribution': '分布',
    'pattern': '模式',
    'arrangement': '排列',
    'organization': '组织',
    'structure': '结构',
    'architecture': '架构',
    'topology': '拓扑',
    'geometry': '几何',
    'shape': '形状',
    'form': '形式',
    'conformation': '构象',
    'configuration': '构型',
    'orientation': '方向',
    'position': '位置',
    'location': '位置',
    'site': '位点',
    'region': '区域',
    'domain': '域',
    'zone': '区',
    'area': '区域',
    'territory': '区域',
    'boundary': '边界',
    'border': '边界',
    'edge': '边缘',
    'margin': '边缘',
    'periphery': '外围',
    'center': '中心',
    'core': '核心',
    'nucleus': '核',
    'cytoplasm': '细胞质',
    'membrane': '膜',
    'wall': '壁',
    'envelope': '包膜',
    'capsule': '荚膜',
    'shell': '壳',
    'coat': '外壳',
    'surface': '表面',
    'interface': '界面',
    'junction': '连接',
    'contact': '接触',
    'gap': '间隙',
    'space': '空间',
    'cavity': '腔',
    'pore': '孔',
    'channel': '通道',
    'tube': '管',
    'vessel': '血管',
    'duct': '导管',
    'tract': '束',
    'fiber': '纤维',
    'filament': '丝',
    'strand': '链',
    'thread': '线',
    'wire': '丝',
    'cable': '缆',
    'rope': '绳',
    'chain': '链',
    'sequence': '序列',
    'series': '系列',
    'array': '阵列',
    'matrix': '矩阵',
    'table': '表',
    'list': '列表',
    'catalog': '目录',
    'inventory': '清单',
    'record': '记录',
    'entry': '条目',
    'item': '项目',
    'element': '元素',
    'component': '组分',
    'part': '部分',
    'piece': '片段',
    'fragment': '片段',
    'segment': '段',
    'section': '部分',
    'division': '分割',
    'partition': '分区',
    'subset': '子集',
    'group': '组',
    'cluster': '簇',
    'family': '家族',
    'class': '类',
    'category': '类别',
    'type': '类型',
    'kind': '种类',
    'sort': '种类',
    'variety': '品种',
    'species': '物种',
    'strain': '菌株',
    'line': '系',
    'clone': '克隆',
    'isolate': '分离株',
    'culture': '培养物',
    'sample': '样本',
    'specimen': '标本',
    'material': '材料',
    'substance': '物质',
    'compound': '化合物',
    'molecule': '分子',
    'atom': '原子',
    'ion': '离子',
    'radical': '自由基',
    'complex': '复合物',
    'mixture': '混合物',
    'solution': '溶液',
    'suspension': '悬浮液',
    'emulsion': '乳液',
    'gel': '凝胶',
    'crystal': '晶体',
    'powder': '粉末',
    'particle': '颗粒',
    'droplet': '小滴',
    'bubble': '气泡',
    'vesicle': '囊泡',
    'organelle': '细胞器',
    'compartment': '区室',
    'lumen': '腔',
    'matrix': '基质',
    'stroma': '基质',
    'ground substance': '基质',
    'extracellular matrix': '细胞外基质',
    'basement membrane': '基底膜',
    'basal lamina': '基板',
    'connective tissue': '结缔组织',
    'epithelium': '上皮',
    'endothelium': '内皮',
    'mesenchyme': '间充质',
    'parenchyma': '实质',
    'stroma': '间质',
    'tissue': '组织',
    'organ': '器官',
    'system': '系统',
    'apparatus': '器',
    'body': '体',
    'organism': '生物体',
    'individual': '个体',
    'population': '群体',
    'community': '群落',
    'ecosystem': '生态系统',
    'environment': '环境',
    'habitat': '栖息地',
    'niche': '生态位',
    'biome': '生物群落',
    'biosphere': '生物圈',
    'earth': '地球',
    'planet': '行星',
    'world': '世界',
    'globe': '全球',
    'universe': '宇宙',
    'cosmos': '宇宙',
    'space': '空间',
    'dimension': '维度',
    'scale': '尺度',
    'level': '水平',
    'tier': '层',
    'layer': '层',
    'stratum': '层',
    'sheet': '片',
    'film': '膜',
    'coating': '涂层',
    'covering': '覆盖物',
    'wrapper': '包装',
    'container': '容器',
    'vessel': '容器',
    'chamber': '室',
    'compartment': '隔室',
    'cell': '细胞',
    'unit': '单位',
    'module': '模块',
    'block': '块',
    'brick': '砖',
    'building block': '构建块',
    'component': '组件',
    'part': '部件',
    'piece': '件',
    'element': '元件',
    'factor': '因子',
    'agent': '因子',
    'mediator': '介质',
    'carrier': '载体',
    'vector': '载体',
    'vehicle': '载体',
    'transporter': '转运体',
    'shuttle': '穿梭体',
    'bridge': '桥',
    'connector': '连接器',
    'linker': '连接子',
    'spacer': '间隔子',
    'separator': '分离器',
    'barrier': '屏障',
    'filter': '过滤器',
    'screen': '筛',
    'sieve': '筛',
    'mesh': '网',
    'net': '网',
    'web': '网',
    'network': '网络',
    'grid': '网格',
    'lattice': '格子',
    'framework': '框架',
    'scaffold': '支架',
    'skeleton': '骨架',
    'backbone': '主链',
    'spine': '脊柱',
    'axis': '轴',
    'pole': '极',
    'end': '端',
    'terminus': '末端',
    'tip': '尖端',
    'peak': '峰',
    'summit': '顶峰',
    'top': '顶部',
    'apex': '顶点',
    'crown': '冠',
    'head': '头',
    'tail': '尾',
    'foot': '足',
    'base': '基部',
    'foundation': '基础',
    'root': '根',
    'origin': '起源',
    'source': '来源',
    'beginning': '开始',
    'start': '开始',
    'initiation': '起始',
    'launch': '启动',
    'activation': '激活',
    'stimulation': '刺激',
    'induction': '诱导',
    'triggering': '触发',
    'catalysis': '催化',
    'promotion': '促进',
    'enhancement': '增强',
    'amplification': '放大',
    'boost': '提升',
    'increase': '增加',
    'elevation': '升高',
    'rise': '上升',
    'growth': '生长',
    'expansion': '扩张',
    'extension': '延伸',
    'elongation': '伸长',
    'stretching': '拉伸',
    'spreading': '扩散',
    'distribution': '分布',
    'dispersion': '分散',
    'dissemination': '传播',
    'circulation': '循环',
    'flow': '流动',
    'stream': '流',
    'current': '流',
    'flux': '通量',
    'movement': '运动',
    'motion': '运动',
    'locomotion': '移动',
    'migration': '迁移',
    'translocation': '易位',
    'displacement': '位移',
    'shift': '转移',
    'change': '变化',
    'alteration': '改变',
    'modification': '修饰',
    'adjustment': '调整',
    'adaptation': '适应',
    'evolution': '进化',
    'development': '发展',
    'progression': '进展',
    'advancement': '进步',
    'improvement': '改进',
    'optimization': '优化',
    'refinement': '精炼',
    'enhancement': '增强',
    'upgrade': '升级',
    'update': '更新',
    'revision': '修订',
    'correction': '纠正',
    'fix': '修复',
    'repair': '修理',
    'maintenance': '维护',
    'preservation': '保存',
    'conservation': '保护',
    'protection': '保护',
    'defense': '防御',
    'resistance': '抗性',
    'tolerance': '耐受性',
    'immunity': '免疫',
    'susceptibility': '易感性',
    'vulnerability': '脆弱性',
    'sensitivity': '敏感性',
    'responsiveness': '反应性',
    'reactivity': '反应性',
    'activity': '活性',
    'function': '功能',
    'role': '作用',
    'purpose': '目的',
    'objective': '目标',
    'goal': '目标',
    'aim': '目标',
    'target': '靶点',
    'focus': '焦点',
    'center': '中心',
    'hub': '枢纽',
    'node': '节点',
    'point': '点',
    'spot': '点',
    'site': '位点',
    'locus': '位点',
    'position': '位置',
    'coordinate': '坐标',
    'address': '地址',
    'location': '位置',
    'place': '地方',
    'venue': '场所',
    'setting': '环境',
    'context': '上下文',
    'background': '背景',
    'condition': '条件',
    'state': '状态',
    'phase': '相',
    'stage': '阶段',
    'period': '时期',
    'era': '时代',
    'epoch': '纪元',
    'age': '年龄',
    'time': '时间',
    'moment': '时刻',
    'instant': '瞬间',
    'second': '秒',
    'minute': '分钟',
    'hour': '小时',
    'day': '天',
    'week': '周',
    'month': '月',
    'year': '年',
    'decade': '十年',
    'century': '世纪',
    'millennium': '千年',
    'generation': '代',
    'cycle': '周期',
    'round': '轮',
    'turn': '转',
    'rotation': '旋转',
    'revolution': '革命',
    'orbit': '轨道',
    'path': '路径',
    'route': '路线',
    'way': '方式',
    'means': '手段',
    'method': '方法',
    'technique': '技术',
    'skill': '技能',
    'ability': '能力',
    'capacity': '容量',
    'capability': '能力',
    'potential': '潜力',
    'power': '力量',
    'strength': '强度',
    'force': '力',
    'energy': '能量',
    'vitality': '活力',
    'vigor': '活力',
    'health': '健康',
    'fitness': '适应性',
    'wellness': '健康',
    'condition': '状况',
    'status': '状态',
    'situation': '情况',
    'circumstance': '环境',
    'scenario': '情景',
    'case': '案例',
    'instance': '实例',
    'example': '例子',
    'sample': '样本',
    'specimen': '标本',
    'model': '模型',
    'template': '模板',
    'pattern': '模式',
    'design': '设计',
    'plan': '计划',
    'scheme': '方案',
    'strategy': '策略',
    'approach': '方法',
    'tactic': '策略',
    'maneuver': '策略',
    'operation': '操作',
    'procedure': '程序',
    'process': '过程',
    'workflow': '工作流程',
    'pipeline': '流水线',
    'assembly line': '装配线',
    'production line': '生产线',
    'manufacturing': '制造',
    'synthesis': '合成',
    'construction': '构建',
    'building': '建筑',
    'creation': '创造',
    'generation': '产生',
    'formation': '形成',
    'establishment': '建立',
    'foundation': '基础',
    'basis': '基础',
    'ground': '基础',
    'support': '支持',
    'backing': '支持',
    'assistance': '帮助',
    'aid': '援助',
    'help': '帮助',
    'service': '服务',
    'facility': '设施',
    'infrastructure': '基础设施',
    'equipment': '设备',
    'apparatus': '装置',
    'device': '设备',
    'instrument': '仪器',
    'tool': '工具',
    'implement': '工具',
    'utensil': '器具',
    'gadget': '小工具',
    'widget': '小部件',
    'component': '组件',
    'part': '部分',
    'section': '部分',
    'segment': '段',
    'portion': '部分',
    'fraction': '分数',
    'percentage': '百分比',
    'proportion': '比例',
    'ratio': '比率',
    'rate': '率',
    'frequency': '频率',
    'occurrence': '发生',
    'incidence': '发生率',
    'prevalence': '患病率',
    'abundance': '丰度',
    'concentration': '浓度',
    'density': '密度',
    'intensity': '强度',
    'magnitude': '大小',
    'extent': '程度',
    'degree': '度',
    'level': '水平',
    'grade': '等级',
    'rank': '等级',
    'class': '类',
    'category': '类别',
    'group': '组',
    'set': '集合',
    'collection': '集合',
    'assembly': '集合',
    'gathering': '聚集',
    'cluster': '簇',
    'bunch': '束',
    'bundle': '捆',
    'package': '包',
    'parcel': '包裹',
    'batch': '批次',
    'lot': '批',
    'series': '系列',
    'sequence': '序列',
    'chain': '链',
    'string': '串',
    'line': '线',
    'row': '行',
    'column': '列',
    'file': '文件',
    'record': '记录',
    'document': '文档',
    'report': '报告',
    'paper': '论文',
    'article': '文章',
    'publication': '出版物',
    'journal': '期刊',
    'magazine': '杂志',
    'book': '书',
    'manual': '手册',
    'guide': '指南',
    'handbook': '手册',
    'reference': '参考',
    'source': '来源',
    'resource': '资源',
    'material': '材料',
    'content': '内容',
    'information': '信息',
    'data': '数据',
    'knowledge': '知识',
    'wisdom': '智慧',
    'insight': '洞察',
    'understanding': '理解',
    'comprehension': '理解',
    'awareness': '意识',
    'consciousness': '意识',
    'perception': '感知',
    'sensation': '感觉',
    'feeling': '感觉',
    'emotion': '情感',
    'mood': '情绪',
    'attitude': '态度',
    'behavior': '行为',
    'conduct': '行为',
    'action': '行动',
    'activity': '活动',
    'performance': '表现',
    'execution': '执行',
    'implementation': '实施',
    'application': '应用',
    'use': '使用',
    'usage': '用法',
    'utilization': '利用',
    'employment': '使用',
    'deployment': '部署',
    'installation': '安装',
    'setup': '设置',
    'configuration': '配置',
    'arrangement': '安排',
    'organization': '组织',
    'structure': '结构',
    'system': '系统',
    'network': '网络',
    'framework': '框架',
    'platform': '平台',
    'foundation': '基础',
    'infrastructure': '基础设施',
    'architecture': '架构',
    'design': '设计',
    'blueprint': '蓝图',
    'plan': '计划',
    'layout': '布局',
    'format': '格式',
    'style': '样式',
    'appearance': '外观',
    'look': '外观',
    'view': '视图',
    'perspective': '视角',
    'angle': '角度',
    'aspect': '方面',
    'facet': '面',
    'side': '侧面',
    'dimension': '维度',
    'feature': '特征',
    'characteristic': '特性',
    'property': '属性',
    'quality': '质量',
    'trait': '特征',
    'attribute': '属性',
    'parameter': '参数',
    'variable': '变量',
    'factor': '因子',
    'element': '元素',
    'component': '组分',
    'ingredient': '成分',
    'constituent': '组成部分',
    'building block': '构建块',
    'unit': '单元',
    'module': '模块',
    'piece': '片段',
    'part': '部分',
    'portion': '部分',
    'section': '部分',
    'segment': '段',
    'fragment': '片段',
    'chunk': '块',
    'bit': '位',
    'byte': '字节',
    'word': '字',
    'term': '术语',
    'phrase': '短语',
    'sentence': '句子',
    'paragraph': '段落',
    'chapter': '章节',
    'section': '部分',
    'volume': '卷',
    'edition': '版本',
    'version': '版本',
    'release': '发布',
    'update': '更新',
    'upgrade': '升级',
    'improvement': '改进',
    'enhancement': '增强',
    'modification': '修改',
    'change': '变化',
    'alteration': '改变',
    'transformation': '转换',
    'conversion': '转换',
    'translation': '翻译',
    'interpretation': '解释',
    'explanation': '说明',
    'clarification': '澄清',
    'illustration': '说明',
    'demonstration': '演示',
    'example': '例子',
    'instance': '实例',
    'case': '案例',
    'study': '研究',
    'analysis': '分析',
    'examination': '检查',
    'investigation': '调查',
    'exploration': '探索',
    'research': '研究',
    'inquiry': '询问',
    'question': '问题',
    'query': '查询',
    'request': '请求',
    'demand': '需求',
    'requirement': '要求',
    'specification': '规格',
    'standard': '标准',
    'criterion': '标准',
    'benchmark': '基准',
    'metric': '度量',
    'measure': '测量',
    'measurement': '测量',
    'quantification': '量化',
    'assessment': '评估',
    'evaluation': '评价',
    'appraisal': '评估',
    'judgment': '判断',
    'decision': '决定',
    'choice': '选择',
    'selection': '选择',
    'option': '选项',
    'alternative': '替代',
    'substitute': '替代品',
    'replacement': '替换',
    'successor': '继任者',
    'heir': '继承者',
    'descendant': '后代',
    'offspring': '后代',
    'progeny': '后代',
    'generation': '代',
    'lineage': '谱系',
    'ancestry': '祖先',
    'heritage': '遗产',
    'inheritance': '继承',
    'legacy': '遗产',
    'tradition': '传统',
    'custom': '习俗',
    'practice': '实践',
    'habit': '习惯',
    'routine': '例行程序',
    'procedure': '程序',
    'protocol': '协议',
    'rule': '规则',
    'regulation': '规定',
    'law': '法律',
    'principle': '原理',
    'theory': '理论',
    'hypothesis': '假设',
    'assumption': '假设',
    'premise': '前提',
    'foundation': '基础',
    'basis': '基础',
    'ground': '基础',
    'reason': '原因',
    'cause': '原因',
    'factor': '因素',
    'agent': '因子',
    'force': '力量',
    'influence': '影响',
    'impact': '影响',
    'effect': '效果',
    'result': '结果',
    'outcome': '结果',
    'consequence': '后果',
    'implication': '含义',
    'significance': '意义',
    'importance': '重要性',
    'relevance': '相关性',
    'relationship': '关系',
    'connection': '连接',
    'association': '关联',
    'correlation': '相关',
    'link': '链接',
    'bond': '键',
    'tie': '联系',
    'attachment': '附着',
    'binding': '结合',
    'interaction': '相互作用',
    'communication': '通信',
    'dialogue': '对话',
    'conversation': '对话',
    'discussion': '讨论',
    'debate': '辩论',
    'argument': '论证',
    'reasoning': '推理',
    'logic': '逻辑',
    'rationale': '理由',
    'justification': '理由',
    'evidence': '证据',
    'proof': '证明',
    'demonstration': '证明',
    'verification': '验证',
    'validation': '验证',
    'confirmation': '确认',
    'support': '支持',
    'backing': '支持',
    'endorsement': '认可',
    'approval': '批准',
    'acceptance': '接受',
    'agreement': '同意',
    'consensus': '共识',
    'harmony': '和谐',
    'unity': '统一',
    'integration': '整合',
    'synthesis': '综合',
    'combination': '组合',
    'mixture': '混合',
    'blend': '混合',
    'fusion': '融合',
    'merger': '合并',
    'union': '联合',
    'alliance': '联盟',
    'partnership': '伙伴关系',
    'collaboration': '合作',
    'cooperation': '合作',
    'teamwork': '团队合作',
    'coordination': '协调',
    'synchronization': '同步',
    'alignment': '对齐',
    'balance': '平衡',
    'equilibrium': '平衡',
    'stability': '稳定性',
    'consistency': '一致性',
    'uniformity': '一致性',
    'regularity': '规律性',
    'pattern': '模式',
    'trend': '趋势',
    'direction': '方向',
    'course': '过程',
    'path': '路径',
    'trajectory': '轨迹',
    'route': '路线',
    'way': '方式',
    'method': '方法',
    'approach': '方法',
    'strategy': '策略',
    'plan': '计划',
    'scheme': '方案',
    'program': '程序',
    'project': '项目',
    'initiative': '倡议',
    'campaign': '运动',
    'effort': '努力',
    'attempt': '尝试',
    'trial': '试验',
    'experiment': '实验',
    'test': '测试',
    'examination': '考试',
    'assessment': '评估',
    'evaluation': '评价',
    'review': '审查',
    'inspection': '检查',
    'audit': '审计',
    'survey': '调查',
    'poll': '民意调查',
    'census': '人口普查',
    'count': '计数',
    'tally': '计数',
    'sum': '总和',
    'total': '总计',
    'aggregate': '总计',
    'accumulation': '积累',
    'collection': '收集',
    'gathering': '收集',
    'assembly': '装配',
    'compilation': '编译',
    'construction': '构建',
    'building': '建筑',
    'creation': '创建',
    'development': '开发',
    'production': '生产',
    'manufacturing': '制造',
    'fabrication': '制作',
    'synthesis': '合成',
    'generation': '生成',
    'formation': '形成',
    'establishment': '建立',
    'foundation': '基础',
    'initiation': '启动',
    'launch': '启动',
    'start': '开始',
    'beginning': '开始',
    'origin': '起源',
    'source': '来源',
    'root': '根源',
    'basis': '基础',
    'ground': '基础',
    'foundation': '基础',
    'base': '基础',
    'bottom': '底部',
    'floor': '地板',
    'surface': '表面',
    'top': '顶部',
    'peak': '峰值',
    'maximum': '最大值',
    'minimum': '最小值',
    'optimum': '最佳',
    'ideal': '理想',
    'perfect': '完美',
    'excellent': '优秀',
    'good': '好',
    'fair': '公平',
    'poor': '差',
    'bad': '坏',
    'worst': '最差',
    'best': '最好',
    'better': '更好',
    'worse': '更差',
    'superior': '优越',
    'inferior': '劣等',
    'high': '高',
    'low': '低',
    'tall': '高',
    'short': '短',
    'long': '长',
    'wide': '宽',
    'narrow': '窄',
    'thick': '厚',
    'thin': '薄',
    'deep': '深',
    'shallow': '浅',
    'big': '大',
    'small': '小',
    'large': '大',
    'tiny': '微小',
    'huge': '巨大',
    'enormous': '巨大',
    'massive': '巨大',
    'giant': '巨大',
    'mini': '迷你',
    'micro': '微',
    'nano': '纳米',
    'pico': '皮',
    'femto': '飞',
    'atto': '阿托',
    'zepto': '仄托',
    'yocto': '幺科托',
    'kilo': '千',
    'mega': '兆',
    'giga': '吉',
    'tera': '太',
    'peta': '拍',
    'exa': '艾',
    'zetta': '泽它',
    'yotta': '尧它'
}

# 分类规则 - 针对web网站和工具
WEB_CATEGORIES = {
    'protein': {
        'name': '蛋白质',
        'keywords': ['protein', 'structure', 'fold', 'domain', 'isoform', 'alphafold', 'structural', 'amino acid', 'peptide', 'enzyme']
    },
    'genomics': {
        'name': '基因组学',
        'keywords': ['genome', 'genomic', 'gene', 'genetic', 'dna', 'sequence', 'chromosome', 'variant', 'mutation', 'gwas', 'snp']
    },
    'plant': {
        'name': '植物生物学',
        'keywords': ['plant', 'arabidopsis', 'rice', 'asteraceae', 'botanical', 'crop', 'agriculture', 'photosynthesis', 'chloroplast']
    },
    'medical': {
        'name': '医学生物学',
        'keywords': ['human', 'disease', 'clinical', 'medical', 'cancer', 'drug', 'therapeutic', 'biomarker', 'patient', 'health']
    },
    'microbiology': {
        'name': '微生物学',
        'keywords': ['bacteria', 'virus', 'viral', 'microbial', 'pathogen', 'microbe', 'prokaryotic', 'archaea']
    },
    'evolution': {
        'name': '进化生物学',
        'keywords': ['evolution', 'phylogen', 'comparative', 'species', 'evolutionary', 'taxonomy', 'tree', 'ancestral']
    },
    'omics': {
        'name': '组学',
        'keywords': ['omics', 'transcriptome', 'proteome', 'metabolome', 'multi-omics', 'rna-seq', 'chip-seq', 'single-cell', 'epigenome']
    },
    'tools': {
        'name': '生物信息工具',
        'keywords': ['tool', 'analysis', 'resource', 'platform', 'service', 'computational', 'bioinformatics', 'software', 'web', 'online', 'server', 'portal', 'browser', 'viewer']
    }
}

def categorize_website(name, description):
    """根据名称和描述给网站分类"""
    text = (name + ' ' + description).lower()
    
    for category_id, category_info in WEB_CATEGORIES.items():
        for keyword in category_info['keywords']:
            if keyword.lower() in text:
                return category_id
    
    return 'tools'  # 默认分类为工具

def translate_description(description):
    """翻译描述"""
    if not description or description == 'nan' or str(description) == 'nan':
        return description
    
    description = str(description)
    
    # 直接查找完整短语的翻译
    desc_lower = description.lower()
    for eng, chn in WEB_TRANSLATIONS.items():
        if eng in desc_lower:
            # 如果找到匹配的短语，进行替换
            description = re.sub(re.escape(eng), chn, description, flags=re.IGNORECASE)
    
    # 如果翻译后与原文不同，返回翻译结果，否则返回原文
    return description

def read_web_sites():
    """读取web网站信息并与现有数据合并"""
    try:
        # 读取web网站Excel文件
        df_web = pd.read_excel('nar2025web.xlsx')
        
        print("Web网站Excel文件的列名:")
        print(df_web.columns.tolist())
        print(f"\nWeb网站数据形状: {df_web.shape}")
        
        # 显示前几行数据
        print("\n前5行Web网站数据:")
        print(df_web.head())
        
        # 读取现有数据
        with open('databases_processed.json', 'r', encoding='utf-8') as f:
            existing_data = json.load(f)
        
        print(f"\n现有数据数量: {len(existing_data)}")
        
        # 处理web网站数据
        web_sites = []
        start_id = len(existing_data) + 1
        
        for index, row in df_web.iterrows():
            site_info = {
                'id': start_id + index,
                'name': str(row.get('Database name', '')),
                'url': str(row.get('URL', '')),
                'short_description': str(row.get('Short description', '')),
                'description': str(row.get('Short description', '')),
                'last_update': '',
                'access': 'Free',
                'data_type': 'website',  # 标记为网站类型
                'resource_type': 'web'   # 区分数据库和网站
            }
            
            # 添加分类
            category = categorize_website(site_info['name'], site_info['short_description'])
            site_info['category'] = category
            site_info['category_name'] = WEB_CATEGORIES[category]['name']
            
            # 添加中文翻译
            site_info['short_description_zh'] = translate_description(site_info['short_description'])
            
            web_sites.append(site_info)
        
        # 为现有数据添加resource_type标记
        for item in existing_data:
            item['resource_type'] = 'database'
        
        # 合并数据
        all_resources = existing_data + web_sites
        
        # 保存合并后的数据
        with open('databases_processed.json', 'w', encoding='utf-8') as f:
            json.dump(all_resources, f, ensure_ascii=False, indent=2)
        
        print(f"\n成功添加了 {len(web_sites)} 个Web网站")
        print(f"总资源数量: {len(all_resources)}")
        
        # 统计分类
        category_stats = {}
        db_stats = {}
        web_stats = {}
        
        for resource in all_resources:
            cat = resource['category']
            res_type = resource.get('resource_type', 'database')
            
            if cat not in category_stats:
                category_stats[cat] = 0
                db_stats[cat] = 0
                web_stats[cat] = 0
            
            category_stats[cat] += 1
            if res_type == 'database':
                db_stats[cat] += 1
            else:
                web_stats[cat] += 1
        
        print("\n更新后的资源分类统计:")
        for cat, count in category_stats.items():
            print(f"  {WEB_CATEGORIES[cat]['name']}: {count}个 (数据库: {db_stats[cat]}, 网站: {web_stats[cat]})")
        
        return all_resources
        
    except Exception as e:
        print(f"处理Web网站数据时出错: {e}")
        import traceback
        traceback.print_exc()
        return []

if __name__ == "__main__":
    resources = read_web_sites()
